gText_HelloAndWelcome::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.$"

gText_WouldYouLikeToRestYourPkmn::
	.string "Would you like to rest your POKéMON?$"

gText_HowCanIAssistYourYourPkmn::
	.string "How can I assist your POKéMON?$"

gText_IllTakeYourPkmn::
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_RestoredPkmnToFullHealth::
	.string "Thank you for waiting.\p"
	.string "We've restored your POKéMON\n"
	.string "to full health.$"

gText_WeHopeToSeeYouAgain::
	.string "We hope to see you again!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_NoticesGoldCard2::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of assisting your POKéMON!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want to rest, am I right?$"

gText_YouWantTheUsual2::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You need assistance, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
	.string "We hope to see you again!$"

gText_NothingToRemember:
	.string "Sorry…\p"
	.string "It appeas that POKéMON doesn't have\n"
	.string "any moves to remember…$"

gText_NothingToForget:
	.string "Sorry…\p"
	.string "It appeas that POKéMON doesn't have\n"
	.string "any moves to forget…$"

gText_NothingToRate:
	.string "Sorry…\p"
	.string "It appeas that POKéMON doesn't have\n"
	.string "a name that can be changed…$"

gText_CantTeachEgg:
	.string "Hmm…\p"
	.string "It appeas that POKéMON is really\n"
	.string "just an EGG.$"
