Route111_EventScript_ItemTM37::
	finditem ITEM_TM37
	end

Route113_EventScript_ItemTM32::
	finditem ITEM_TM32
	end

Route115_EventScript_ItemTM01::
	finditem ITEM_TM01
	end

FieryPath_EventScript_ItemTM06::
	finditem ITEM_TM06
	end

MeteorFalls_1F_1R_EventScript_ItemTM23::
	finditem ITEM_TM23
	end

MeteorFalls_B1F_2R_EventScript_ItemTM02::
	finditem ITEM_TM02
	end

AbandonedShip_Room_B1F_EventScript_ItemTM13::
	finditem ITEM_TM13
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18::
	finditem ITEM_TM18
	end

ScorchedSlab_EventScript_ItemTM11::
	finditem ITEM_TM11
	end

SafariZone_Northwest_EventScript_ItemTM22::
	finditem ITEM_TM22
	end

MtPyre_6F_EventScript_ItemTM30::
	finditem ITEM_TM30
	end

MtPyre_Exterior_EventScript_ItemTM48::
	finditem ITEM_TM48
	end

ShoalCave_LowTideIceRoom_EventScript_ItemTM07::
	finditem ITEM_TM07
	end

SeafloorCavern_Room9_EventScript_ItemTM26::
	finditem ITEM_TM26
	end

VictoryRoad_B1F_EventScript_ItemTM29::
	finditem ITEM_TM29
	end
